### ISSUE TITLE
Cannot configure self-managed EBSCSIDriver

### ISSUE THREAD

**Issue by norseto** [terraform-kops/terraform-provider-kops#133]
To prevent kOps from installing the EBSCSIDriver, I set the managed setting of ebs_csi_driver to false as shown below:
```
cloud_provider {
  aws {
    ebs_csi_driver {
      enabled = true
      managed = false
    }
  }
}
```
The result of kops get cluster -oyaml is as follows. The false value is omitted as nil.
```
  cloudConfig:
    awsEBSCSIDriver:
      enabled: true
```
However, if managed is nil, kOps will behave the same as if managed = true, which means it will install the EBSCSIDriver.
For this reason, it is not possible to configure the self-managed EBSCSIDriver.

From what I can see from the source, it seems that the problem can be solved by setting `managed` to `required`, but I am not sure if this is the correct way to do it.

Provider Version: 1.30.1

**Comment by argoyle** [comment]
Aaah, there probably needs to be some special handling of that one similar to a few other fields.
