### ISSUE TITLE
Publish to terraform

### ISSUE THREAD

**Issue by clayrisser** [terraform-kops/terraform-provider-kops#20]
@sl1pm4t great to see that you published this to the terraform registry!

https://registry.terraform.io/providers/terraform-kops/kops/latest

**Comment by clayrisser** [comment]
I'm going to keep my provider at https://registry.terraform.io/providers/clayrisser/kops/latest just so I can iterate and make changes without effecting this project. I will consider this repo to be the stable version.

**Comment by sl1pm4t** [comment]
I had trouble getting the Terraform registry to detect this org and repo. In the end I used my alternate GH account @mattaerial  to sign in and publish the provider.
