### ISSUE TITLE
Error: missing expected [

### ISSUE THREAD

**Issue by sohel2020** [terraform-kops/terraform-provider-kops#44]
**Trace LOG**
<img width="1512" alt="image" src="https://github.com/terraform-kops/terraform-provider-kops/assets/7457974/5cca6893-3967-4295-b075-831b82ba497a">

**Error**
<img width="671" alt="image" src="https://github.com/terraform-kops/terraform-provider-kops/assets/7457974/b30ea0ae-ed44-4dae-ac55-e4e1f564d0b2">

**Terraform Code**
<img width="962" alt="image" src="https://github.com/terraform-kops/terraform-provider-kops/assets/7457974/2ba34a0c-229c-4dbf-9a5f-ef61a4db4b62">

**kops provider version**: 1.28.5

I don't know where I'm missing `[` in **config_store**

**Comment by sohel2020** [comment]
> I don't see anything obvious in the code snippet posted above, but sometimes the line number reported by Terraform doesn't match the line where the problem actually exists. I suspect in this case, Terraform is saying line 4 because it's the start of the resources block that has a problem _somewhere_.

If you look at Trace log diagnostic summary it's complaining `config_store`

![image](https://github.com/terraform-kops/terraform-provider-kops/assets/7457974/be9ed0ae-2cec-48d0-add3-168aa1ade2e2)

**Comment by sohel2020** [comment]
I solved the problem by manually fixing the `terraform.tfstate` file.

my config_store was like 
```
"config_store" : "",
```

So I modify it to

```
"config_store": [
  {
    "base": "s3://bedex-kops/k8s.bdx-staging.gg"
  }
],
```

**Comment by sl1pm4t** [comment]
Thanks for the update. Did you upgrade from an earlier version of the kops provider (perhaps the eddycharly version)?

**Comment by sohel2020** [comment]
> Thanks for the update. Did you upgrade from an earlier version of the kops provider (perhaps the eddycharly version)? 

Yes
