### ISSUE TITLE
Add GossipConfig & DNSControllerGossipConfig cluster spec blocks

### ISSUE THREAD

**Issue by dkulchinsky** [terraform-kops/terraform-provider-kops#46]
For deployments that use the Gossip based DNS, kops currently runs two gossip configurations in parallel:
- `mesh` (primary)
- `memberlistmesh` (secondary)

The intent was to allow the deprecated `mesh` gossip protocol to be phased out and `memberlistmesh` promoted to primary (following by disabling the deprecated `mesh` gossip once it's defined as secondary)

Unfortunately, this work was never quite completed upstream in kops, it was tracked in https://github.com/kubernetes/kops/issues/7436 for a while but closed without getting completed.

`mesh` gossip presents several challenges when cluster reaches a certain size.

There is a fairly simple procedure for promoting `memberlistmesh` to be the primary gossip, described [here](https://github.com/kubernetes/kops/issues/7436#issuecomment-548104333), unfortunately since the provider doesn't expose the `GossipConfig` & `DNSControllerGossipConfig` blocks in the cluster resource spec we don't have a way to apply this change with the provider.

from a quick look at `gen-tf-code`, it appears that both blocks are excluded: https://github.com/terraform-kops/terraform-provider-kops/blob/14d0485227f4620980c81a8eecda264d2bf6f985/hack/gen-tf-code/main.go#L137

not sure why?

**Comment by sl1pm4t** [comment]
Hi @dkulchinsky - I'm not sure why either as I've never used the Gossip mode. Only @eddycharly would have the history.

**Comment by eddycharly** [comment]
Hey! I don't remember exactly why it was excluded. It's worth trying to unexclude IMHO

**Comment by dkulchinsky** [comment]
Thanks @sl1pm4t & @eddycharly

Taking a stab at removing these from the exclusion list, but hitting a snag with the code generator:
```
❯ make gen
2024/05/13 11:08:16 loading packages...
2024/05/13 11:08:20 generating schemas, expanders and flatteners...
panic: template: hack/gen-tf-code/templates/doc.tpl:44:7: executing "hack/gen-tf-code/templates/doc.tpl" at <subResources .>: error calling subResources: runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
main.executeTemplate({0x1059fa740, 0x1055b70a0}, {0x103979fff, 0x22}, {0x103905b67, 0xf}, {0x1400121d548, 0xa}, {0x140d5a5ff40, 0x5, ...})
	/Users/dkulchinsky/github-clones/terraform-provider-kops/hack/gen-tf-code/templates.go:32 +0x2b4
main.buildDoc({0x1059fa740, 0x1055b70a0}, {0x103905b67, 0xf}, {0x140d5a5ff40, 0x5, 0x8})
	/Users/dkulchinsky/github-clones/terraform-provider-kops/hack/gen-tf-code/main.go:34 +0x9c
main.build({0x1038dd60c, 0x8}, {0x103905b67, 0xf}, 0x140d103a890, {0x140012218b8, 0x8a, 0x1400073c700?})
	/Users/dkulchinsky/github-clones/terraform-provider-kops/hack/gen-tf-code/main.go:82 +0x53c
main.main()
	/Users/dkulchinsky/github-clones/terraform-provider-kops/hack/gen-tf-code/main.go:99 +0x5264
exit status 2
make: *** [gen-tf-code] Error 1
```

didn't dig into it yet as I'm not too familiar with the code gen machinery, so if you have any thoughts/pointers - would be great.

**Comment by dkulchinsky** [comment]
my attempt to address this in https://github.com/terraform-kops/terraform-provider-kops/pull/53

**Comment by eddycharly** [comment]
@dkulchinsky you probably need to register the structs if you remove them from the exclude list

**Comment by dkulchinsky** [comment]
> @dkulchinsky you probably need to register the structs if you remove them from the exclude list

Thanks @eddycharly! I believe I figured it out and have a proposed change in https://github.com/terraform-kops/terraform-provider-kops/pull/53
